name: ball_balance_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - opencv
  - pandas
  - numpy
  - pip
  - pip:
      - ultralytics
      - tensorflow
      - pyserial
      - matplotlib
      - albumentations
      - cocotb
      - torch
      - torchvision
      - Pillow
      - scikit-learn
      - scipy
      - sounddevice
      - soundfile
      - pyyaml
      - requests
      - fastmcp
      - resampy
      - onnxruntime
      - tf2onnx
      - onnx2torch
      - openvino
      - pillow-heif
