import argparse
from pathlib import Path
import re

import numpy as np
import tensorflow as tf


LAYER_PREFIX_RE = re.compile(r"[^0-9a-zA-Z_]+")


def sanitize_name(name: str) -> str:
    name = name.replace("/", "_").replace("-", "_")
    name = LAYER_PREFIX_RE.sub("_", name)
    name = name.strip("_")
    if not name:
        raise ValueError("Cannot sanitize empty layer name")
    return name


def format_float_array(name: str, array: np.ndarray, indent: str = "    ") -> str:
    flat = np.asarray(array, dtype=np.float32).reshape(-1)
    values = []
    for value in flat:
        if np.isnan(value) or np.isinf(value):
            raise ValueError(f"Invalid numeric value in {name}: {value}")
        values.append(f"{value:.8e}f")

    if not values:
        return f"static const float {name}[] = {{}};\n"

    lines = []
    line = indent
    for value in values:
        if len(line) + len(value) + 2 > 100:
            lines.append(line)
            line = indent + value + ", "
        else:
            line += value + ", "
    lines.append(line.rstrip(", "))

    return f"static const float {name}[] = {{\n" + "\n".join(lines) + "\n};\n"


def format_shape_macros(base_name: str, shape: tuple[int, ...]) -> list[str]:
    macros = []
    if len(shape) == 0:
        macros.append(f"#define {base_name}_SHAPE_0 1")
        return macros

    macros.append(f"#define {base_name}_NDIMS {len(shape)}")
    for dim, size in enumerate(shape):
        macros.append(f"#define {base_name}_SHAPE_{dim} {size}")
    macros.append(f"#define {base_name}_SIZE {int(np.prod(shape))}")
    return macros


def format_weight_name(weight_obj_name: str) -> str:
    clean_name = weight_obj_name.split("/")[-1]
    clean_name = clean_name.split(":")[0]
    return sanitize_name(clean_name).upper()


def export_model_weights(model_path: Path, output_path: Path, hls_style: bool = False) -> None:
    model = tf.keras.models.load_model(str(model_path))
    output_path.parent.mkdir(parents=True, exist_ok=True)

    header_guard = sanitize_name(output_path.stem).upper() + "_H"
    lines = [
        f"// AUTO-GENERATED by export_audio_weights.py -- do not edit by hand.",
        f"#ifndef {header_guard}",
        f"#define {header_guard}",
        "",
        "#include <cstdint>",
        "",
    ]

    for layer_index, layer in enumerate(model.layers, start=1):
        weights = layer.get_weights()
        if not weights:
            continue

        layer_name = sanitize_name(layer.name).upper()
        if len(layer.weights) == len(weights):
            weight_objects = layer.weights
        else:
            weight_objects = []

        for idx, weight in enumerate(weights, start=1):
            if weight.ndim == 0:
                weight = weight.reshape((1,))

            if weight_objects:
                suffix = format_weight_name(weight_objects[idx - 1].name)
            elif idx == 1 and weight.ndim > 0 and layer.trainable_weights and weight.shape == layer.trainable_weights[0].shape:
                suffix = "KERNEL"
            elif idx == 2 and len(weights) >= 2:
                suffix = "BIAS"
            else:
                suffix = f"W{idx}"

            array_name = f"{layer_name}_{suffix}"
            shape = np.asarray(weight).shape

            lines.append(f"// layer: {layer.name} ({type(layer).__name__})")
            if hls_style:
                lines.extend(format_shape_macros(array_name, tuple(shape)))
            else:
                shape_name = sanitize_name(f"{layer_name}_{suffix}_shape")
                lines.append(format_int_array(shape_name, np.array(shape)))

            lines.append(format_float_array(array_name, weight))
            lines.append("")

    lines.append(f"#endif // {header_guard}\n")
    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Exported weights from {model_path} to {output_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Export a Keras audio classifier model's weights into a C header file."
    )
    parser.add_argument(
        "--model",
        type=Path,
        default=Path(__file__).resolve().parent
        / "models"
        / "audio_command_classifier"
        / "best_classifier.keras",
        help="Path to the saved Keras model checkpoint.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parent
        / "models"
        / "audio_command_classifier"
        / "audio_classifier_weights.h",
        help="Path to the generated C header file.",
    )
    parser.add_argument(
        "--hls",
        action="store_true",
        help="Emit an HLS-style header with shape macros instead of shape arrays.",
    )
    args = parser.parse_args()
    export_model_weights(args.model, args.output, hls_style=args.hls)
